### ISSUE TITLE
Bug in namban

### ISSUE THREAD

**Issue by Thecode764** [parchlinuxB/namban#14]
Hi. what's this error?

localuser:root being added to access control list
Traceback (most recent call last):
  File "/usr/lib/namban/src/namban.py", line 1, in <module>
    import application
  File "/usr/lib/namban/src/application.py", line 2, in <module>
    gi.require_version("Gtk","4.0")
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 125, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 4.0
localuser:root being removed from access control list

**Comment by ARS101** [comment]
Hi, please mention your distribution name and version.

So we can see if it's a packaging issue or a code issue.

**Comment by Thecode764** [comment]
i use parch linux kde and i downloaded latest version from official site @ARS101

**Comment by ARS101** [comment]
From what I can understand. It is a dependency issue.

I intend to write a fresh and proper PKGBUILD script to package it on AUR.
Will fix this issue on my way.

Stay tuned for that.

> i use parch linux kde and i downloaded latest version from official site @ARS101
