### ISSUE TITLE
There's no error message for wrong input

### ISSUE THREAD

**Issue by Gnkalk** [parchlinuxB/namban#5]
When you input wrong in Dns input box, the OK button went disable but there isn't any message or anything to tell you why button disabled 
![image](https://github.com/parchlinuxB/namban/assets/74614163/ed1409c1-113c-44af-a111-0520b7749952)

You can change input box color or show something (error icon for example) to help user

**Comment by meshya** [comment]
Hi @Gnkalk ,

Thank you for your suggestion! We appreciate your input and are pleased to inform you that the requested feature has been added to our roadmap.

Thanks for contributing to the project!

Best regards,
[meshya]
