### ISSUE TITLE
Add screenshot(s) to README

### ISSUE THREAD

**Issue by mmahmoudian** [parchlinuxB/namban#8]
Since this is a GUI tool, perhaps it would be extra nice to have some screenshots available so that potential new users can see what it does.

**Comment by meshya** [comment]
Thank you for your suggestion! We have added screenshots to the README to help potential new users see what the tool does. We appreciate your feedback and hope this improves the user experience.

Best regards,

[meshya]

**Comment by mmahmoudian** [comment]
@meshya 
I just can see it in the README. Have you pished it to remote? Can you provide the commit hash that contains this change?

**Comment by meshya** [comment]
I just answered your issue first, then started editing the readme :)
